<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.js"></script>
	<title>How to Create a Simple REST API With Slim Framework</title>
	<style>
	.thead-inverse th {
    color: #fff;
    background-color: #373a3c;
}
	</style>
</head>
<body>
	<div class="container" style="margin:50px;">
		<h1>Welcome to Slim Framework</h1>
		<h2>First Application Walkthrough</h2>
		
		</div>
	</body>
</html>